apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-demo-template
  title: Simple Demo Template
  description: Creates a repo with a single catalog-info.yaml file.
spec:
  owner: ali509
  type: service

  # 1. Input Form
  parameters:
    - title: Basic Information
      required: [name]
      properties:
        name:
          title: Name
          type: string
          description: Unique name for the component
    - title: Choose Location
      required: [repoUrl]
      properties:
        repoUrl:
          title: GitHub Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: [github.com]

  # 2. Actions to take
  steps:
    - id: fetch-base
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        description: "Manifest for ${{ parameters.name }}"
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
