apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl | parseRepoUrl | fqdn }}/${{ values.repoUrl | parseRepoUrl | owner }}/${{ values.repoUrl | parseRepoUrl | repo }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
