apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: "Created from the Simple Demo Template"
spec:
  type: service
  lifecycle: experimental
  owner: ali509
